PublicRadioInternational/pri-component-library

- index.js
- src/components/00_global/colors.css
- src/components/Molecules/CardItem/CardItem.component.js
- src/components/Molecules/CardItem/CardItem.css
- src/components/Molecules/CardItem/CardItem.test.js
- src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
- src/components/Molecules/molecules.story.js
- src/components/Organisms/CardList/CardList.component.js
- src/components/Organisms/CardList/CardList.css
- src/components/Organisms/CardList/CardList.test.js
- src/components/Organisms/CardList/__snapshots__/CardList.test.js.snap
- src/components/Organisms/organisms.story.js
- Adds Card (list) and styling, category support
> PRIAPI-128: Card List

- src/components/00_global/colors.css
- src/components/Organisms/CardList/CardList.component.js
- Updates the CardList categories PropTypes definition so it can take any valid categories.
> HOTFIX: Update CardList categories

- src/components/Molecules/Hero/Hero.component.js
- src/components/Molecules/Hero/Hero.test.js
- src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap
- src/components/Molecules/molecules.story.js
- Adjusts program links so they can have a (optional) different url than the story url.
> HOTFIX: All Hero program links to have a different url.

- src/components/Organisms/Main/Main.css
- Fixes grid to match prototype widths
> fix(layout): grid tweaks to match prototype

- src/components/00_global/global.css
- src/components/Organisms/Main/Main.css
- Fixes for medium screen layout (padding) and responsive elements
> PRIAPI-128: medium layout and responsive fixes

- src/components/00_global/global.css
- src/components/Molecules/molecules.story.js
- Adds a global blockquote style
> HOTFIX: add blockquote style

- index.js
- src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap
- src/components/Molecules/List/List.component.js
- src/components/Molecules/List/List.css
- src/components/Molecules/List/__snapshots__/List.test.js.snap
- src/components/Molecules/MenuList/MenuList.component.js
- src/components/Molecules/MenuList/MenuList.css
- src/components/Molecules/MenuList/MenuList.test.js
- src/components/Molecules/MenuList/__snapshots__/MenuList.test.js.snap
- src/components/Molecules/molecules.story.js
- src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
- src/components/Organisms/Header/__snapshots__/Header.test.js.snap
- src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Menu List component and Quick Links example in storybook
- Not crazy about how I had to pass the styling for the individual items through to the root component (list). I'd rather style them at the Menu list level if someone can help me think through that piece.
> PRIAPI-132: Quick links

- src/components/00_global/global.css
- src/components/Molecules/CardItem/CardItem.component.js
- src/components/Molecules/CardItem/CardItem.css
- src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
> PIRAPI-128: Homepage CardList video auto height

- index.js
- src/components/00_global/colors.css
- src/components/00_global/global.css
- src/components/Atoms/Button/Button.css
- src/components/Molecules/TextBlock/TextBlock.component.js
- src/components/Molecules/TextBlock/TextBlock.css
- src/components/Molecules/TextBlock/TextBlock.test.js
- src/components/Molecules/TextBlock/__snapshots__/TextBlock.test.js.snap
- src/components/Molecules/molecules.story.js
- Adds Text Block component and About implementation
](http://localhost:9001/?selectedKind=Molecules%2FTextBlock&selectedStory=About&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
> PRIAPI-133: About block

- src/components/Molecules/MenuList/MenuList.css
- src/components/Molecules/TextBlock/TextBlock.css
- src/components/Organisms/Main/Main.css
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Adds filler homepage content into component lib for testing/styling
> Home content

- index.js
- src/components/Atoms/Button/Button.css
- src/components/Atoms/Form/Form.css
- src/components/Molecules/TextBlock/TextBlock.component.js
- src/components/Molecules/TextBlock/TextBlock.css
- src/components/Molecules/TextBlock/TextBlock.test.js
- src/components/Molecules/TextBlock/__snapshots__/TextBlock.test.js.snap
- src/components/Molecules/molecules.story.js
- src/components/Organisms/BlockList/BlockList.component.js
- src/components/Organisms/BlockList/BlockList.css
- src/components/Organisms/BlockList/BlockList.test.js
- src/components/Organisms/BlockList/__snapshots__/BlockList.test.js.snap
- src/components/Organisms/Footer/Footer.css
- src/components/Organisms/Main/Main.css
- src/components/Organisms/organisms.story.js
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Adds Block list component, more flexibility to text block component
> PRIAPI-134: Block List component

- src/components/Atoms/Button/Button.css
- src/components/Organisms/organisms.story.js
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Fixes, implements buttons in 3 ways section (block list)
> PRIAPI-134: button fixes

- src/components/Atoms/LazyLoad/LazyLoad.component.js
- Wrap polyfill in conditional per https://github.com/zeit/next.js/wiki/FAQ
> fix(ssr): only load polyfill in browser

- src/components/Molecules/Accordion/Accordion.component.js
- Change CSS ordering in accordion component
> PRIAPI-165: reorder styles in accordion

- src/components/00_global/stratas.css
- src/components/Molecules/CtaMessage/CtaMessage.css
- src/components/Molecules/Dropdown/Dropdown.css
- src/components/Molecules/Hero/Hero.css
- src/components/Organisms/Header/Header.css
- src/components/Organisms/Main/Main.css
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- add global strata variables
- remove z-index from elements that do not need it
- replace z-index values with strata variables
> PRIAPI-174: Standardize UI z-index scheme

- src/components/00_global/colors.css
- src/components/Molecules/CtaMessage/CtaMessage.component.js
- src/components/Molecules/List/List.css
- src/components/Molecules/molecules.story.js
> Release June 12, 2018

- package-lock.json
- src/components/Molecules/molecules.story.js
- src/components/Organisms/CardList/CardList.component.js
- src/components/Organisms/organisms.story.js
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
#123 
- Removes Program Logs from the card list
> #123 removes show logo in Card List

- src/components/Organisms/Main/Main.css
- Fixes so The World card appears at the top of the main column
> HOTFIX: adjust css grid

- src/components/00_global/colors.css
- src/components/00_global/global.css
- src/components/Atoms/Button/Button.css
- src/components/Atoms/DropdownItem/DropdownItem.css
- src/components/Molecules/CardItem/CardItem.css
- src/components/Molecules/CtaMessage/CtaMessage.css
- src/components/Molecules/Hero/Hero.css
- src/components/Molecules/List/List.css
- src/components/Molecules/MenuList/MenuList.css
- src/components/Molecules/Teaser/TeaserItem.css
- src/components/Organisms/Header/MainMenu.css
> HOTFIX: Restyle dark buttons

- src/components/Atoms/Button/Button.css
- src/components/Molecules/TextBlock/TextBlock.css
- src/components/Organisms/CardList/CardList.test.js
- src/components/Pages/Home/Home.component.js
- src/components/Pages/Home/__snapshots__/Home.test.js.snap
- restyles text boxes for TW and reinserts into the layout.
> FE#136 TW about box
