src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/CardItem.test.js, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Organisms/CardList/CardList.component.js, src/components/Organisms/organisms.story.js
- Adjusts the CardItem component such that it does not require a link or title (requirements for freeforms).
- Improves tests for CardItem.
- Adds ability for `blurb` property to contain any valid JSX node.
- Adjusts the CardList component so it doesn't render images if they don't exist.
=> HOTFIX: Url and title not required in CardItem

src/components/Organisms/CardList/CardList.css, src/components/Organisms/organisms.story.js
- Updates card list header colors to match the pattern that Patrick set up (pris-the-world)
=> HOTFIX: Update card list header colors 

package.json, src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/CardItem.css, src/components/Molecules/CardItem/CardItem.test.js, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Molecules/molecules.story.js, yarn.lock
- Adds styling for the freeform CardItems.
- Adjusts the CardItem component so that it doesn't render images if they aren't provided.
- Adjusts the CardItem component so images aren't linked if a link isn't provided.
=> HOTFIX: Freeform CardItem styles

src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/CardItem.css, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
- Makes the freeform CardList content render in a div, all other card list types render in a paragraph.
- Improves the CardItem component's approach to conditional rendering.
=> HOTFIX: Freeform blurb is div and has no margin

src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Organisms/Teaser/TeaserList.css, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Addresses a minor styling issue on the Latest Content teaser list PR: https://github.com/PublicRadioInternational/pri-frontend/pull/15
=> HOTFIX: tweak teaserList header style

src/components/Organisms/CardList/CardList.component.js, src/components/Organisms/CardList/CardList.css, src/components/Organisms/CardList/__snapshots__/CardList.test.js.snap, src/components/Organisms/organisms.story.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Adds consistent height to the card title [with](http://localhost:9001/?selectedKind=Organisms%2FCardList&selectedStory=Card%20List%20with%20Image&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) or [without](http://localhost:9001/?selectedKind=Organisms%2FCardList&selectedStory=Without%20Image&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) the image
=> PRIAPI-158: consistent card list title height

package.json, src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Molecules/molecules.story.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap, yarn.lock
- Uses `dangerouslySetInnerHtml` for the `CardItem` blurbs so that we can remove `react-html-parser` from the frontend side.
=> fix: set innerHtml for CardItem blurbs

src/components/Organisms/CardList/CardList.css, src/components/Organisms/Footer/Footer.css, src/components/Organisms/Main/Main.css, src/components/Pages/Home/Home.component.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap, yarn.lock
- Space between LayoutMainList and LayoutMainList2 should be `1rem`
- Space between CardList siblings should be `1rem`
- LayoutMain should clear floated children non-desktop sizes
=> fix(main): normalize spacing of sections and cardlists

.babelrc, .storybook/config.js, __mocks__/intersection-observer.js, index.js, package.json, src/components/00_global/global.css, src/components/Atoms/LazyLoad/LazyLoad.component.js, src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/CardItem.test.js, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Molecules/Hero/Hero.component.js, src/components/Molecules/Hero/Hero.test.js, src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap, src/components/Pages/Home/Home.test.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap, yarn.lock
- Adds lazy loading component to be used to wrap any direct descendent with the `src` attribute
- Adds lazy loading for images in card item, hero components
=> PRIAPI-153: Lazy Load

src/components/Molecules/CtaMessage/CtaMessage.css, src/components/Molecules/molecules.story.js
-The load under padding was too large. This adjusts it.
=> HOTFIX: fix padding in load under

src/components/Molecules/CtaMessage/CtaMessage.component.js, src/components/Molecules/CtaMessage/CtaMessage.css, src/components/Molecules/CtaMessage/__snapshots__/CtaMessage.test.js.snap
- Updates load under title styling to match live
- Changes CTA message wrapper element to `<aside>` so its `<h3>` title has its own outline context
=> HOTFIX: Update load under title style to match live changes

src/components/Organisms/Header/Header.component.js, src/components/Organisms/Header/__snapshots__/Header.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Adds the correct donate url in the header.
=> HOTFIX: Header donate link url

src/components/Organisms/CardList/CardList.component.js, src/components/Organisms/CardList/CardList.css, src/components/Organisms/CardList/__snapshots__/CardList.test.js.snap, src/components/Organisms/organisms.story.js, src/components/Pages/Home/Home.component.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- add support for header without a link
- doesn't render header if title is not set
- refactor CardList props to not have a category-centric nomenclature
- refactor CardList header to not depend on a flexbox link wrapper
- add `id` prop to CardList
- update organism and Home component to make use of prop changes
=> PRISB-266: Update to support custom headers with optional link

src/components/Molecules/CtaMessage/CtaMessage.component.js, src/components/Molecules/CtaMessage/CtaMessage.css, src/components/Molecules/CtaMessage/__snapshots__/CtaMessage.test.js.snap, src/components/Molecules/molecules.story.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Allows CTA message descriptions to contain HTML markup.
=> PRISB-283: GDRP cookie disclaimer messages require links to policy pages.

src/components/Molecules/CtaMessage/CtaMessage.component.js
- Renders dismiss button when action button is not defined. Useful for informative messages such as cookie notices.
=> fix(ctamessage): render dismiss button when action note defined

src/components/Molecules/CtaMessage/CtaMessage.component.js, src/components/Molecules/molecules.story.js
- CTA Message actions do not require a URL.
=> HOTFIX: CTA Message action url is optional

src/components/00_global/colors.css, src/components/Molecules/List/List.css, src/components/Molecules/molecules.story.js
- Adds Quick Link colors for Living on Earth (LOE) & Takeaway (TT)
- Changes GlobalPost (GP) Quick Link color to Blue (from red, since everything else is red)
=> PRISB-295: add Quick Link colors for Takeaway and LOE

src/components/Organisms/Header/MainMenu.component.js, src/components/Organisms/Header/__snapshots__/Header.test.js.snap, src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- `Science of Happiness` should be `The Science of Happiness`
=> PRISB-303: fix typo in main menu

src/components/Molecules/CtaMessage/CtaMessage.component.js, src/components/Molecules/CtaMessage/CtaMessage.css, src/components/Molecules/molecules.story.js
- Restyles the pull down banner for an upcoming announcement.
- NOTE: Not all the elements will be in use with the announcement, but they are present in the component.
=> Hotfix: Restyle pulldown menu

src/components/Organisms/Header/Header.component.js
- Adds a link to the listen dropdown
=> PRISB-415: adds Live Stream Schedule link to header

src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/Hero/Hero.component.js, src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap, src/components/Molecules/Teaser/TeaserItem.component.js, src/components/Molecules/Teaser/__snapshots__/TeaserItem.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Removes the audio indication icon from the display. I believe this to be confusing users without the persistent player (at which point we will introduce play buttons).
=> PRISB-416: Remove hasAudio icon

src/components/Organisms/Header/Header.component.js
- Removes the AWL link in the newsletter dropdown
=> PRISB-442: remove AWL newsletter signup

src/components/Organisms/Header/Header.component.js, src/components/Organisms/Header/MainMenu.component.js, src/components/Organisms/Header/__snapshots__/Header.test.js.snap, src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
#106 
- Updates the donations link in the header to point to proper pages.
=> fix(header): change donation links in menu

src/components/Molecules/Accordion/Accordion.component.js, src/components/Molecules/List/List.component.js
- Sets default value for `<List>` prop 'listItems` to `[]`. Was `{}`.
- Sets default value for `<Accordion>` prop 'accordionList` to `[]`. Was `{}`.
=> HOTFIX: list items prop should default to empty array

src/components/Molecules/CardItem/CardItem.component.js, src/components/Molecules/CardItem/CardItem.css, src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap, src/components/Molecules/molecules.story.js, src/components/Organisms/organisms.story.js, src/components/Pages/Home/Home.component.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
#113
- Adds link list to freeform card items
- Adds images to freeform card items
- Updates card item styles to accommodate layout changes
=> #113: Add support for freeform card link list

src/components/Molecules/CardItem/CardItem.css, src/components/Organisms/organisms.story.js
- Cleans up layout styles of card items across screen sizes. There were some contradicting techniques used that made overrides inconsistent.
=> HOTFIX: Cleanup card layout styles

src/components/Organisms/Footer/Footer.component.js, src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Adds CBP as funder
- All images point to media.pri.org (Share the same image as the one on the Drupal site footer)
=> feat(footer): add new funder

src/components/Molecules/CtaMessage/CtaMessage.css, src/components/Molecules/molecules.story.js, src/components/Organisms/Footer/Footer.component.js, src/components/Organisms/Footer/Footer.css, src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap, src/components/Pages/Home/Home.component.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- I overlooked an error in the footer component with the logo SVG. I moved the height and width to the CSS (so I could adjust the size on mobile)
- After pulling into the frontend, I noticed that the load under styling needed better spacing.
=> HOTFIX: fix overlooked error (and some minor styling)

src/components/Organisms/Footer/Footer.component.js, src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Removes the BBC logo from the site footer
=> Remove BBC logo from footer

src/components/Organisms/Footer/Footer.component.js, src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap, src/components/Pages/Home/__snapshots__/Home.test.js.snap
- Updates WGBH footer assets to be GBH.
=> Swap gbh logo

src/components/Atoms/Button/ButtonLink.component.js, src/components/Atoms/Button/__snapshots__/Button.test.js.snap, src/components/Molecules/List/List.component.js, src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap, src/components/Organisms/Header/Header.component.js, src/components/Organisms/Header/MainMenu.component.js, src/components/Organisms/organisms.story.js, src/components/Pages/Home/__snapshots__/Home.test.js.snap
Closes #148 
- Adds additional attributes from menu data to links
=> #148: Transfer menu item attrs to links
